# Generated by Django 2.2.1 on 2020-04-30 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid', models.CharField(max_length=30, null=True, unique=True, verbose_name='设备编号')),
                ('name', models.CharField(max_length=50, verbose_name='设备名称')),
                ('model', models.CharField(blank=True, max_length=30, verbose_name='设备型号')),
                ('spec', models.CharField(blank=True, max_length=30, verbose_name='设备规格')),
                ('manufacturer', models.CharField(blank=True, max_length=50, null=True, verbose_name='生产厂商')),
                ('produced_on', models.DateField(blank=True, null=True, verbose_name='生产日期')),
                ('acquired_at', models.DateTimeField(auto_now_add=True, verbose_name='购置日期')),
                ('expired_on', models.DateField(blank=True, null=True, verbose_name='保质日期')),
                ('status', models.CharField(default='审核中', max_length=20, verbose_name='状态')),
                ('quantity', models.IntegerField(default=1, verbose_name='数量')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='单价')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='设备类别名称')),
            ],
        ),
        migrations.CreateModel(
            name='BaseAppModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('status', models.CharField(default='审核中', max_length=10, verbose_name='审批状态')),
                ('opinion', models.TextField(blank=True, verbose_name='审批意见')),
                ('asset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='asset.Asset', verbose_name='关联设备')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baseappmodel_reviewed_assets', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('transactor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baseappmodel_transacted_assets', to=settings.AUTH_USER_MODEL, verbose_name='经办人')),
            ],
        ),
        migrations.CreateModel(
            name='AssetCreate',
            fields=[
                ('baseappmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='asset.BaseAppModel')),
                ('credentials', models.FileField(blank=True, upload_to='credentials/%Y/%m', verbose_name='建账证明')),
            ],
            bases=('asset.baseappmodel',),
        ),
        migrations.CreateModel(
            name='AssetFix',
            fields=[
                ('baseappmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='asset.BaseAppModel')),
                ('contact', models.CharField(default='', max_length=20, verbose_name='维修方联系方式')),
                ('returned_at', models.DateTimeField(blank=True, null=True, verbose_name='维修结束时间')),
            ],
            bases=('asset.baseappmodel',),
        ),
        migrations.CreateModel(
            name='AssetScrap',
            fields=[
                ('baseappmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='asset.BaseAppModel')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='报废原因')),
            ],
            bases=('asset.baseappmodel',),
        ),
        migrations.AddField(
            model_name='asset',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_category_assets', to='asset.AssetCategory', verbose_name='设备类别'),
        ),
        migrations.AddField(
            model_name='asset',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_department_assets', to='department.Department', verbose_name='所在部门'),
        ),
    ]
