# Generated by Django 2.2.1 on 2020-04-25 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='设备类别名称')),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True, verbose_name='设备编号')),
                ('name', models.CharField(max_length=50, verbose_name='设备名称')),
                ('model', models.CharField(blank=True, max_length=30, unique=True, verbose_name='设备型号')),
                ('spec', models.CharField(blank=True, max_length=30, null=True, verbose_name='设备规格')),
                ('manufacturer', models.CharField(blank=True, max_length=50, null=True, verbose_name='生产厂商')),
                ('produced_on', models.DateField(blank=True, null=True, verbose_name='生产日期')),
                ('acquired_on', models.DateField(auto_now_add=True, verbose_name='购置日期')),
                ('expire_on', models.DateField(blank=True, null=True, verbose_name='保质日期')),
                ('department', models.CharField(blank=True, max_length=30, null=True, verbose_name='所在部门')),
                ('status', models.CharField(default='Good', max_length=30, verbose_name='状态')),
                ('number', models.PositiveIntegerField(default=1, verbose_name='数量')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='单价')),
                ('note', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='asset.AssetCategory', verbose_name='设备类别')),
                ('transactor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to=settings.AUTH_USER_MODEL, verbose_name='经办人')),
            ],
        ),
    ]
