# Generated by Django 2.2.1 on 2020-05-01 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetsku',
            name='skuid',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='货格编号'),
        ),
    ]
