# Generated by Django 2.2.1 on 2020-05-02 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asset', '0001_initial'),
        ('department', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='baseappmodel',
            name='reviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baseappmodel_reviewed_assets', to=settings.AUTH_USER_MODEL, verbose_name='审批人'),
        ),
        migrations.AddField(
            model_name='baseappmodel',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baseappmodel_sku', to='asset.AssetSKU', verbose_name='关联SKU'),
        ),
        migrations.AddField(
            model_name='baseappmodel',
            name='transactor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baseappmodel_transacted_assets', to=settings.AUTH_USER_MODEL, verbose_name='经办人'),
        ),
        migrations.AddField(
            model_name='assetsku',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skus', to='asset.Asset', verbose_name='所属设备'),
        ),
        migrations.AddField(
            model_name='assetset',
            name='app',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_sets_app', to='asset.BaseAppModel', verbose_name='关联申请'),
        ),
        migrations.AddField(
            model_name='assetset',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='department.Department', verbose_name='所在部门'),
        ),
        migrations.AddField(
            model_name='assetset',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assetset_manager', to=settings.AUTH_USER_MODEL, verbose_name='负责人'),
        ),
        migrations.AddField(
            model_name='assetset',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='asset.AssetSKU', verbose_name='所属货格'),
        ),
        migrations.AddField(
            model_name='assetset',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assetset_user', to=settings.AUTH_USER_MODEL, verbose_name='使用人'),
        ),
        migrations.AddField(
            model_name='asset',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='asset.AssetCategory', verbose_name='设备类别'),
        ),
    ]
