# Generated by Django 2.2.1 on 2020-05-02 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetset',
            name='app',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_sets_app', to='asset.BaseAppModel', verbose_name='关联申请'),
        ),
    ]
