# Generated by Django 2.2.1 on 2020-05-07 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetborrowreturn',
            name='borrowed_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='借出时间'),
        ),
    ]
