# Generated by Django 2.2.1 on 2020-04-29 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_auto_20200429_2014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='expire_on',
            new_name='expired_on',
        ),
        migrations.AlterField(
            model_name='asset',
            name='acquired_on',
            field=models.DateField(auto_now_add=True, verbose_name='购置日期'),
        ),
    ]
