# Generated by Django 2.2.1 on 2020-05-07 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_auto_20200507_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetborrowreturn',
            name='returned_at',
            field=models.DateTimeField(null=True, verbose_name='实际归还时间'),
        ),
    ]
