# Generated by Django 2.2.1 on 2020-06-03 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_auto_20200603_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='aid',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
