# Generated by Django 2.2.1 on 2020-04-25 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_auto_20200425_2155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='number',
            new_name='quantity',
        ),
    ]
