# Generated by Django 2.2.1 on 2020-05-07 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_auto_20200507_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetset',
            name='status',
            field=models.CharField(default='审核中', max_length=20, verbose_name='状态'),
        ),
    ]
