# Generated by Django 2.2.1 on 2020-05-06 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_baseappmodel_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetBorrowReturn',
            fields=[
                ('baseappmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='asset.BaseAppModel')),
                ('borrow_date', models.DateTimeField(blank=True, null=True, verbose_name='借出时间')),
                ('ext_return_date', models.DateTimeField(blank=True, null=True, verbose_name='预计归还时间')),
                ('return_date', models.DateTimeField(blank=True, null=True, verbose_name='实际归还时间')),
            ],
            options={
                'verbose_name': 'Asset borrow return application',
                'verbose_name_plural': 'Asset borrow return applications',
            },
            bases=('asset.baseappmodel',),
        ),
    ]
