# Generated by Django 2.2.1 on 2020-05-07 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_baseappmodel_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetBorrowReturn',
            fields=[
                ('baseappmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='asset.BaseAppModel')),
                ('borrowed_at', models.DateTimeField(verbose_name='借出时间')),
                ('estimate_return_on', models.DateField(verbose_name='预计归还时间')),
                ('returned_at', models.DateTimeField(verbose_name='实际归还时间')),
            ],
            options={
                'verbose_name': 'Asset borrow return application',
                'verbose_name_plural': 'Asset borrow return applications',
            },
            bases=('asset.baseappmodel',),
        ),
        migrations.CreateModel(
            name='AssetChange',
            fields=[
                ('baseappmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='asset.BaseAppModel')),
                ('change_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='变更类型')),
                ('change_field', models.CharField(max_length=50, verbose_name='变动字段')),
                ('change_description', models.CharField(max_length=100, verbose_name='变动内容')),
            ],
            options={
                'verbose_name': 'Asset change application',
                'verbose_name_plural': 'Asset change applications',
            },
            bases=('asset.baseappmodel',),
        ),
    ]
