# Generated by Django 2.2.1 on 2020-05-14 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_auto_20200507_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetborrowreturn',
            name='returned_status',
            field=models.CharField(max_length=10, null=True, verbose_name='归还时状态'),
        ),
    ]
