# Generated by Django 2.2.1 on 2020-05-14 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0005_assetborrowreturn_returned_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetborrowreturn',
            name='returned_at',
        ),
        migrations.AddField(
            model_name='assetborrowreturn',
            name='returned_on',
            field=models.DateField(null=True, verbose_name='实际归还时间'),
        ),
    ]
