# Generated by Django 2.2.1 on 2020-04-22 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['id'], 'permissions': (('create_user', 'Can create user'), ('read_user', 'Can read user'), ('update_user', 'Can update user'), ('delete_user', 'Can delete user')), 'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profile'},
        ),
    ]
