# Generated by Django 2.2.1 on 2020-04-22 04:06

from django.db import migrations
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200422_1143'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['id'], 'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profile'},
        ),
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
                ('objects', user.models.UserManager()),
            ],
        ),
    ]
