# Generated by Django 2.2.1 on 2020-04-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=30, null=True, unique=True, verbose_name='部门'),
        ),
    ]
